CREATE OR REPLACE STREAM CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_QUEUE_STREAM
ON TABLE CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_QUEUE
APPEND_ONLY = TRUE;


SELECT SYSTEM$STREAM_HAS_DATA('CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_QUEUE_STREAM');