LIST @CUSTOMER.FILE_PROCESSING.CLIENT_DATA_STAGE PATTERN='.*updated_sample\\.csv';

CREATE OR REPLACE STAGE CUSTOMER.FILE_PROCESSING.CLIENT_DATA_STAGE
  URL = 's3://inferlytica-snowflake-client-data-151562994023-us-east-1-an/uploads/'
  STORAGE_INTEGRATION = S3_INGEST_DATA_INTEGRATION;