 CREATE OR REPLACE STAGE DATA_PROVIDER_SSA.RAW.PROVIDER_DATA_STAGE
  URL = 's3://inferlytica-snowflake-provider-data-151562994023-us-east-1-an/uploads/'
  STORAGE_INTEGRATION = S3_INGEST_DATA_INTEGRATION;