SELECT *
FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE;

ALTER DYNAMIC TABLE CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE REFRESH;

DELETE
FROM CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS;

DELETE 
FROM CUSTOMER.ANALYTICS.BATCH_GENDER_SUMMARY;

SELECT *
FROM INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.GENDER_OUTPUT_MODEL_RESULTS;

CALL CUSTOMER.FILE_PROCESSING.DELIVER_GENDER_RESULTS(1, 101);

DESC TABLE CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE;

SELECT *
FROm CUSTOMER.ANALYTICS.BATCH_GENDER_SUMMARY;

CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.DELIVER_GENDER_RESULTS(CLIENT_ID NUMBER (32,0), BATCH_ID NUMBER(32,0), MODEL_VERSION VARCHAR DEFAULT 'v0.01')
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    IS_MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT BOOLEAN DEFAULT FALSE;
    BATCH_PROCESSED_TS timestamp_ntz DEFAULT CURRENT_TIMESTAMP();
BEGIN

    SELECT MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT INTO IS_MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT
    FROM CUSTOMER.MANAGEMENT.CLIENT
    WHERE ID = :CLIENT_ID;

    INSERT INTO CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS(
        CLIENT_ID, BATCH_ID, RECORD_ID, PREDICTED_GENDER, REPORTABLE_GENDER, CONFIDENCE_LEVEL, MAX_PROBABILITY, PROBABILITY_GAP, MODEL_VERSION, PROCESSED_TS
    )
    SELECT CLIENT_ID, BATCH_ID, RECORD_ID, SSA_PREDICTED_GENDER, SSA_REPORTABLE_GENDER, SSA_CONFIDENCE_LEVEL, SSA_MAX_PROBABILITY, SSA_PROBABILITY_GAP, :MODEL_VERSION, LOAD_TS
    FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE
    WHERE CLIENT_ID = :CLIENT_ID AND BATCH_ID = :BATCH_ID
    ORDER BY 
        TRY_TO_NUMBER(RECORD_ID) IS NULL,   -- puts numbers first
        TRY_TO_NUMBER(RECORD_ID),           -- numeric sort
        RECORD_ID;

    UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
    SET PROCESSED_TS = :BATCH_PROCESSED_TS
    WHERE CLIENT_ID = :CLIENT_ID 
    AND ID = :BATCH_ID;

    insert into CUSTOMER.ANALYTICS.BATCH_GENDER_SUMMARY (
    CLIENT_ID,
    BATCH_ID,
    MODEL_VERSION,
    TOTAL_RECORDS,
    USABLE_FIRST_NAME_RECORDS,
    SSA_LOOKUP_MATCH_RECORDS,
    SSA_LOOKUP_MATCH_RATE,
    HIGH_CONFIDENCE_RECORDS,
    MEDIUM_CONFIDENCE_RECORDS,
    LOW_CONFIDENCE_RECORDS,
    AMBIGUOUS_RECORDS,
    REPORTABLE_M_RECORDS,
    REPORTABLE_F_RECORDS,
    REPORTABLE_U_RECORDS,
    PROCESSED_TS
    )
    select
        CLIENT_ID,
        BATCH_ID,
        :MODEL_VERSION,
        count(*) as TOTAL_RECORDS,
        sum(case when FIRST_NAME_MISSING_FLAG = 0 then 1 else 0 end) as USABLE_FIRST_NAME_RECORDS,
        sum(case when SSA_LOOKUP_MATCH_FLAG = 1 then 1 else 0 end) as SSA_LOOKUP_MATCH_RECORDS,
        case 
            when count(*) = 0 then 0
            else sum(case when SSA_LOOKUP_MATCH_FLAG = 1 then 1 else 0 end) / count(*)
        end as SSA_LOOKUP_MATCH_RATE,
        sum(case when SSA_CONFIDENCE_LEVEL = 'HIGH' then 1 else 0 end) as HIGH_CONFIDENCE_RECORDS,
        sum(case when SSA_CONFIDENCE_LEVEL = 'MEDIUM' then 1 else 0 end) as MEDIUM_CONFIDENCE_RECORDS,
        sum(case when SSA_CONFIDENCE_LEVEL = 'LOW' then 1 else 0 end) as LOW_CONFIDENCE_RECORDS,
        sum(case when SSA_CONFIDENCE_LEVEL = 'AMBIGUOUS' then 1 else 0 end) as AMBIGUOUS_RECORDS,
        sum(case when SSA_REPORTABLE_GENDER = 'M' then 1 else 0 end) as REPORTABLE_M_RECORDS,
        sum(case when SSA_REPORTABLE_GENDER = 'F' then 1 else 0 end) as REPORTABLE_F_RECORDS,
        sum(case when SSA_REPORTABLE_GENDER = 'U' then 1 else 0 end) as REPORTABLE_U_RECORDS,
        :BATCH_PROCESSED_TS as PROCESSED_TS
    from CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE
    where CLIENT_ID = :CLIENT_ID
      and BATCH_ID = :BATCH_ID
    group by
        CLIENT_ID,
        BATCH_ID;
        
    --Move Participant data into model improvement location
    IF (:IS_MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT) THEN
        INSERT INTO INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.GENDER_OUTPUT_MODEL_RESULTS
                (
            CLIENT_ID,
            BATCH_ID,
            RECORD_ID,
            FIRST_NAME_RAW,
            FIRST_NAME_CLEAN,
            LAST_NAME_RAW,
            LAST_NAME_CLEAN,
            ZIP_RAW,
            ZIP5,
            SSA_MALE_PROBABILITY,
            SSA_FEMALE_PROBABILITY,
            SSA_CONFIDENCE_LEVEL,
            SSA_LOOKUP_MATCH_FLAG,
            SSA_PREDICTED_GENDER,
            SSA_REPORTABLE_GENDER,
            MODEL_VERSION
        )
        SELECT 
            CLIENT_ID, 
            BATCH_ID, 
            RECORD_ID, 
            FIRST_NAME_RAW, 
            FIRST_NAME_CLEAN, 
            LAST_NAME_RAW, 
            LAST_NAME_CLEAN,
            ZIP_RAW, 
            ZIP5, 
            SSA_MALE_PROBABILITY, 
            SSA_FEMALE_PROBABILITY,  
            SSA_CONFIDENCE_LEVEL, 
            SSA_LOOKUP_MATCH_FLAG,
            SSA_PREDICTED_GENDER,
            SSA_REPORTABLE_GENDER,
            :MODEL_VERSION
        FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE
        WHERE CLIENT_ID = :CLIENT_ID AND BATCH_ID = :BATCH_ID
        ORDER BY 
            TRY_TO_NUMBER(RECORD_ID) IS NULL,   -- puts numbers first
            TRY_TO_NUMBER(RECORD_ID),           -- numeric sort
            RECORD_ID;
    END IF;

    --REMOVE SOURCE DATA
    DELETE
    FROM CUSTOMER.RAW.PERSON_INPUT
    WHERE CLIENT_ID = :CLIENT_ID
    AND BATCH_ID = :BATCH_ID;

    --This will cascade the deletion from source to output analysis, but not the result data(CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS).
    ALTER DYNAMIC TABLE CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE REFRESH;
    
    RETURN 'SUCCESS';
END;
$$;