CREATE OR REPLACE TABLE INFERLYTICA.CONFIGURATION.ENRICHMENT_ATTRIBUTE (
    ID VARCHAR(36) NOT NULL,
    CODE VARCHAR NOT NULL,
    LABEL VARCHAR NOT NULL,
    SORT_ORDER NUMBER(10,0),
    CONSTRAINT PK_ENRICHMENT_ATTRIBUTE PRIMARY KEY (ID)
);

CREATE OR REPLACE TABLE INFERLYTICA.CONFIGURATION.ENRICHMENT_ATTRIBUTE_DETAIL (
    ID VARCHAR(36) NOT NULL,
    ATTRIBUTE_ID VARCHAR(36) NOT NULL,
    CODE VARCHAR NOT NULL,
    LABEL VARCHAR NOT NULL,
    SORT_ORDER NUMBER(10,0),
    OUTPUT_FIELD_NAME VARCHAR,
    CONSTRAINT PK_ENRICHMENT_ATTRIBUTE_DETAIL PRIMARY KEY (ID),
    CONSTRAINT FK_ENRICHMENT_ATTRIBUTE_DETAIL_ATTRIBUTE
        FOREIGN KEY (ATTRIBUTE_ID)
        REFERENCES INFERLYTICA.CONFIGURATION.ENRICHMENT_ATTRIBUTE (ID)
);


SELECT *
FROM INFERLYTICA.CONFIGURATION.ENRICHMENT_ATTRIBUTE_DETAIL;

SELECT *
FROM INFERLYTICA.CONFIGURATION.ENRICHMENT_ATTRIBUTE;