CREATE OR REPLACE VIEW INFERLYTICA.REPORTING.VW_MODEL_IMPROVEMENT_AGG_UNMATCHED_LOW_QUALITY
AS
select
    CLIENT_ID,
    BATCH_ID,
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(SSA_LOOKUP_MATCH_FLAG = 0) AS UNMATCHED_RECORDS,
    UNMATCHED_RECORDS/TOTAL_RECORDS AS PERCENT_UNMATCHED,
    COUNT_IF(SSA_CONFIDENCE_LEVEL = 'LOW') AS MATCHED_LOW_RECORDS,
    MATCHED_LOW_RECORDS/TOTAL_RECORDS AS PERCENT_LOW,
    COUNT_IF(SSA_CONFIDENCE_LEVEL = 'AMBIGUOUS') AS MATCHED_AMBIGUOUS_RECORDS,
    MATCHED_AMBIGUOUS_RECORDS/TOTAL_RECORDS AS PERCENT_AMGIGUOUS,
    MATCHED_LOW_RECORDS + MATCHED_AMBIGUOUS_RECORDS AS MATCH_LOW_AMBIGUOUS_RECORDS,
    MATCH_LOW_AMBIGUOUS_RECORDS/TOTAL_RECORDS AS PERCENT_LOW_AMGIGUOUS
from INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.GENDER_OUTPUT_MODEL_RESULTS
group by CLIENT_ID, BATCH_ID
order by CLIENT_ID, BATCH_ID, PERCENT_UNMATCHED desc;

SELECT *
FROM INFERLYTICA.REPORTING.VW_MODEL_IMPROVEMENT_UNMATCHED;

DROP VIEW  INFERLYTICA.REPORTING.VW_MODEL_IMPROVEMENT_AGG_UNMATCH_LOW_QUALITY;