CREATE OR REPLACE VIEW INFERLYTICA.REPORTING.VW_MODEL_IMPROVEMENT_UNMATCHED
AS
select
    CLIENT_ID,
    BATCH_ID,
    COUNT_IF(SSA_LOOKUP_MATCH_FLAG = 0) AS UNMATCHED_RECORDS,
    COUNT(*) AS TOTAL_RECORDS,
    UNMATCHED_RECORDS/TOTAL_RECORDS * 100 AS PERCENT_UNMATCHED
from INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.GENDER_OUTPUT_MODEL_RESULTS
group by CLIENT_ID, BATCH_ID
order by CLIENT_ID, BATCH_ID, PERCENT_UNMATCHED desc;