CREATE OR REPLACE VIEW INFERLYTICA.REPORTING.VW_MODEL_IMPROVEMENT_LOW_CONFIDENCE(
    CLIENT_ID,
    BATCH_ID,
    RECORD_ID,
    FIRST_NAME_RAW,
    FIRST_NAME_CLEAN,
    ZIP_RAW,
    ZIP5,
    SSA_PREDICTED_GENDER,
    SSA_REPORTABLE_GENDER,
    SSA_MALE_PROBABILITY,
    SSA_FEMALE_PROBABLITY,
    SSA_CONFIDENCE_LEVEL,
    MODEL_VERSION
) AS
    SELECT 
        CLIENT_ID,
        BATCH_ID,
        RECORD_ID,
        FIRST_NAME_RAW,
        FIRST_NAME_CLEAN,
        ZIP_RAW,
        ZIP5,
        SSA_PREDICTED_GENDER,
        SSA_REPORTABLE_GENDER,
        SSA_MALE_PROBABILITY,
        SSA_FEMALE_PROBABILITY,
        SSA_CONFIDENCE_LEVEL,
        MODEL_VERSION
    FROM 
        INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.GENDER_OUTPUT_MODEL_RESULTS
    WHERE SSA_CONFIDENCE_LEVEL IN ('LOW', 'AMBIGUOUS');


SELECT *
FROM INFERLYTICA.REPORTING.VW_MODEL_IMPROVEMENT_LOW_CONFIDENCE;


DESC TABLE INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.GENDER_OUTPUT_MODEL_RESULTS;