CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION CUSTOMER_FILE_PROCESSING_SUPABASE_EDGE_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (CUSTOMER.FILE_PROCESSING.SUPABASE_EDGE_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (CUSTOMER.FILE_PROCESSING.UPLOAD_DELIVERY_WEBHOOK_SECRET)
  ENABLED = TRUE;

GRANT READ ON SECRET CUSTOMER.FILE_PROCESSING.UPLOAD_DELIVERY_WEBHOOK_SECRET TO ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION CUSTOMER_FILE_PROCESSING_SUPABASE_EDGE_ACCESS_INTEGRATION TO ROLE ACCOUNTADMIN;


ALTER EXTERNAL ACCESS INTEGRATION CUSTOMER_FILE_PROCESSING_SUPABASE_EDGE_ACCESS_INTEGRATION
SET ALLOWED_AUTHENTICATION_SECRETS = (
    CUSTOMER.FILE_PROCESSING.UPLOAD_DELIVERY_WEBHOOK_SECRET,
    CUSTOMER.FILE_PROCESSING.DOWNLOAD_STATUS_WEBHOOK_SECRET,
    CUSTOMER.MANAGEMENT.BATCH_APPROVAL_WEBHOOK_SECRET
);