USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR COMPUTE_WH_LIMIT
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE COMPUTE_WH
  SET RESOURCE_MONITOR = COMPUTE_WH_LIMIT;