CREATE OR REPLACE STREAM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS_STREAM
ON TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS
APPEND_ONLY = TRUE;


SELECT SYSTEM$STREAM_HAS_DATA('CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS_STREAM');