CREATE OR REPLACE STREAM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_QUEUE_STREAM
ON TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_QUEUE
APPEND_ONLY = TRUE;


SELECT SYSTEM$STREAM_HAS_DATA('CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_QUEUE_STREAM');