CREATE SCHEMA INFERLYTICA.CLIENT_MODEL_IMPROVEMENT;

DESC TABLE CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE;

CREATE OR REPLACE TRANSIENT TABLE INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.OUTPUT_MODEL_RESULTS
(
    CLIENT_ID NUMBER(32,0),
    BATCH_ID NUMBER(32,0 ),
    RECORD_ID VARCHAR,
    FIRST_NAME_RAW VARCHAR,
    FIRST_NAME_CLEAN VARCHAR,
    LAST_NAME_RAW VARCHAR,
    LAST_NAME_CLEAN VARCHAR,
    ZIP_RAW VARCHAR,
    ZIP5 VARCHAR,
    SSA_MALE_PROBABILITY NUMBER(38,6),
    SSA_FEMALE_PROBABILITY NUMBER(38,6),
    SSA_CONFIDENCE_LEVEL VARCHAR(9),
    SSA_LOOKUP_MATCH_FLAG NUMBER(1,0),
    SSA_PREDICTED_GENDER VARCHAR(1),
    SSA_REPORTABLE_GENDER VARCHAR(1),
    MODEL_VERSION VARCHAR,
    OPTED_IN_DATA_LOADED_TS timestamp_ntz default current_timestamp() 
);