CREATE OR REPLACE TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED_LANDING_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_FILE_TO_RAW();

ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK RESUME;