CREATE OR REPLACE TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED_LANDING_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_FILE_TO_RAW();

ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK RESUME;

--Make task serverless
ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK SUSPEND;
ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK UNSET WAREHOUSE;
ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK
SET USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 10, -- check every 10 seconds if it's triggered
    SERVERLESS_TASK_MAX_STATEMENT_SIZE = XSMALL, --limit to xsmall
    TARGET_COMPLETION_INTERVAL = '15 MINUTES'; -- A performance target Snowflake uses to size compute for a serverless task.

ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK RESUME;


ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK
SET USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 10;

DESC TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK;



EXECUTE TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK;
--TARGET_COMPLETION_INTERVAL
--SERVERLESS_TASK_MAX_STATEMENT_SIZE
--USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS

SELECT *
FROM TABLE(
  CUSTOMER.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'PROCESS_CLIENT_DATA_UPLOAD_TASK',
    RESULT_LIMIT => 50
  )
)
ORDER BY SCHEDULED_TIME DESC;

Uncaught exception of type 'STATEMENT_ERROR' on line 87 at position 4 : SQL compilation error:
Object 'CUSTOMER.FILE_PROCESSING.CREDIT_APPROVAL_QUEUE' does not exist or not authorized.