CREATE OR REPLACE TASK CUSTOMER.FILE_PROCESSING.SEND_CLIENT_BATCH_NOTIFICATIONS_TASK
  USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 10
  SERVERLESS_TASK_MAX_STATEMENT_SIZE = XSMALL
  TARGET_COMPLETION_INTERVAL = '15 MINUTES'
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_NOTIFICATIONS_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.SEND_CLIENT_BATCH_NOTIFICATIONS();

ALTER TASK CUSTOMER.FILE_PROCESSING.SEND_CLIENT_BATCH_NOTIFICATIONS_TASK RESUME;
