CREATE OR REPLACE TASK CUSTOMER.FILE_PROCESSING.TRIGGER_BATCH_COMPLETION_TASK
  USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 10
  SERVERLESS_TASK_MAX_STATEMENT_SIZE = XSMALL
  TARGET_COMPLETION_INTERVAL = '15 MINUTES'
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_COMPLETION_QUEUE_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.ENRICHMENT_COMPLETE();

ALTER TASK CUSTOMER.FILE_PROCESSING.TRIGGER_BATCH_COMPLETION_TASK RESUME;

SELECT *
FROM TABLE(
  CUSTOMER.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TRIGGER_BATCH_COMPLETION_TASK',
    RESULT_LIMIT => 50
  )
)
ORDER BY SCHEDULED_TIME DESC;