CREATE OR REPLACE TASK CUSTOMER.FILE_PROCESSING.TRIGGER_UPDATE_SUPABASE_BATCH_DOWNLOAD_TASK
  USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 10
  SERVERLESS_TASK_MAX_STATEMENT_SIZE = XSMALL
  TARGET_COMPLETION_INTERVAL = '15 MINUTES'
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_READY_QUEUE_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.UPDATE_SUPABASE_BATCH_DOWNLOAD();

ALTER TASK CUSTOMER.FILE_PROCESSING.TRIGGER_UPDATE_SUPABASE_BATCH_DOWNLOAD_TASK RESUME;

SELECT SYSTEM$STREAM_HAS_DATA('CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_READY_QUEUE_STREAM');

SELECT *
FROM TABLE(
  CUSTOMER.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TRIGGER_UPDATE_SUPABASE_BATCH_DOWNLOAD_TASK',
    RESULT_LIMIT => 50
  )
)
ORDER BY SCHEDULED_TIME DESC;

--Python Interpreter Error:
Traceback (most recent call last):
  File "_udf_code.py", line 167, in run
    raise fatal_error
  File "_udf_code.py", line 61, in run
    download_status = row["DOWNLOAD_STATUS_KEY"]
                      ~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "<site-packages>/snowflake/snowpark/row.py", line 151, in __getitem__
    return self._named_values[item]
           ~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'DOWNLOAD_STATUS_KEY'
 in function UPDATE_SUPABASE_BATCH_DOWNLOAD with handler run