CREATE OR REPLACE TASK CUSTOMER.FILE_PROCESSING.TRIGGER_ENRICHMENT_TASK
  USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 10
  SERVERLESS_TASK_MAX_STATEMENT_SIZE = XSMALL
  TARGET_COMPLETION_INTERVAL = '15 MINUTES'
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.START_ENRICHMENT_PROCESS();

ALTER TASK CUSTOMER.FILE_PROCESSING.TRIGGER_ENRICHMENT_TASK RESUME;

SELECT *
FROM TABLE(
  CUSTOMER.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TRIGGER_ENRICHMENT_TASK',
    RESULT_LIMIT => 50
  )
)
ORDER BY SCHEDULED_TIME DESC;