CREATE DATABASE DATA_PROVIDER_SSA;
CREATE SCHEMA DATA_PROVIDER_SSA.RAW;
CREATE OR REPLACE TRANSIENT TABLE DATA_PROVIDER_SSA.RAW.FIRST_NAME_GENDER_QUANTITY_YEAR
(   
    FIRST_NAME VARCHAR(1024),
    GENDER VARCHAR(1),
    QUANTITY NUMBER(32, 0),
    YEAR NUMBER(4,0)
);