CREATE SCHEMA CUSTOMER.MANAGEMENT;

CREATE OR REPLACE TABLE CUSTOMER.MANAGEMENT.CLIENT 
(
    ID NUMBER(32,0) IDENTITY(1,1),
    ABBREVIATION VARCHAR(5),
    NAME VARCHAR(250),
    NOTES VARCHAR,
    CREATED_TS timestamp_ntz default current_timestamp(),
    CONSTRAINT primary_key_id PRIMARY KEY (ID)
    
)

;

ALTER TABLE CUSTOMER.MANAGEMENT.CLIENT 
ADD COLUMN MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT BOOLEAN DEFAULT FALSE;

UPDATE  CUSTOMER.MANAGEMENT.CLIENT 
SET MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT = TRUE;
