CREATE SCHEMA CUSTOMER.ANALYTICS;

create or replace transient dynamic table CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE
target_lag = downstream
warehouse = COMPUTE_WH
refresh_mode = incremental
initialize = on_create
as
select
    P.CLIENT_ID,
    P.BATCH_ID,
    P.RECORD_ID,
    P.FIRST_NAME_RAW,
    P.LAST_NAME_RAW,
    P.ZIP_RAW,
    P.FIRST_NAME_CLEAN,
    P.LAST_NAME_CLEAN,
    P.ZIP5,
    P.FIRST_NAME_MISSING_FLAG,
    P.ZIP_UNUSABLE_FLAG,
    P.FIRST_NAME_LENGTH,
    P.LOAD_TS,
    case
        when L.FIRST_NAME is not null then 1
        else 0
    end as SSA_LOOKUP_MATCH_FLAG,
    L.MALE_QTY as SSA_MALE_QTY,
    L.FEMALE_QTY as SSA_FEMALE_QTY,
    L.TOTAL_QTY as SSA_TOTAL_QTY,
    L.MALE_PROBABILITY as SSA_MALE_PROBABILITY,
    L.FEMALE_PROBABILITY as SSA_FEMALE_PROBABILITY,
    L.MAX_PROBABILITY as SSA_MAX_PROBABILITY,
    L.PROBABILITY_GAP as SSA_PROBABILITY_GAP,
    L.PREDICTED_GENDER as SSA_PREDICTED_GENDER,
    L.CONFIDENCE_LEVEL as SSA_CONFIDENCE_LEVEL,
    L.IS_RARE_NAME as SSA_IS_RARE_NAME,
    L.REPORTABLE_GENDER as SSA_REPORTABLE_GENDER
from CUSTOMER.STAGE.PERSON_INPUT_CLEAN P
left join DATA_PROVIDER_SSA.ANALYTICS.FIRST_NAME_GENDER_QUANTITY_LOOKUP L
    on P.FIRST_NAME_CLEAN = L.FIRST_NAME;