CREATE SCHEMA CUSTOMER.MANAGEMENT;

CREATE OR REPLACE TABLE CUSTOMER.MANAGEMENT.CLIENT 
(
    ID NUMBER(32,0) IDENTITY(1,1),
    ABBREVIATION VARCHAR(5),
    NAME VARCHAR(250),
    NOTES VARCHAR,
    CREATED_TS timestamp_ntz default current_timestamp(),
    CONSTRAINT primary_key_id PRIMARY KEY (ID)
    
)

;

CREATE SCHEMA CUSTOMER.FILE_PROCESSING;

CREATE OR REPLACE TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
(
    ID NUMBER(32,0) IDENTITY(1,1),
    CLIENT_ID NUMBER(32,0),
    FILE_NAME VARCHAR(1000),
    NOTES VARCHAR,
    CREATED_TS timestamp_ntz default current_timestamp(),

     CONSTRAINT foreign_key_client_id
        FOREIGN KEY (CLIENT_ID)
        REFERENCES CUSTOMER.MANAGEMENT.CLIENT(ID)
);