CREATE SCHEMA CUSTOMER.STAGE;

create or replace transient dynamic table CUSTOMER.STAGE.PERSON_INPUT_CLEAN
target_lag = DOWNSTREAM
warehouse = COMPUTE_WH
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
as
select
    CUSTOMER_ID,
    BATCH_ID,
    RECORD_ID,
    FIRST_NAME as FIRST_NAME_RAW,
    LAST_NAME as LAST_NAME_RAW,
    ZIP as ZIP_RAW,
    INFERLYTICA.UTILITY.NORMALIZE_NAME(FIRST_NAME) as FIRST_NAME_CLEAN,
    INFERLYTICA.UTILITY.NORMALIZE_NAME(LAST_NAME) as LAST_NAME_CLEAN,
    INFERLYTICA.UTILITY.NORMALIZE_ZIP5(ZIP) as ZIP5,
    case when FIRST_NAME_CLEAN is null then 1 else 0 end as FIRST_NAME_MISSING_FLAG,
    case when LAST_NAME_CLEAN is null then 1 else 0 end as LAST_NAME_MISSING_FLAG,
    case when ZIP5 is null then 1 else 0 end as ZIP_UNUSABLE_FLAG,
    length(FIRST_NAME_CLEAN) as FIRST_NAME_LENGTH,
    length(LAST_NAME_CLEAN) as LAST_NAME_LENGTH,
    LOAD_TS
from CUSTOMER.RAW.PERSON_INPUT;


SELECT *
FROM CUSTOMER.STAGE.PERSON_INPUT_CLEAN;