
CREATE SCHEMA CUSTOMER.FILE_PROCESSING;

CREATE OR REPLACE TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
(
    ID NUMBER(32,0) IDENTITY(1,1),
    CLIENT_ID NUMBER(32,0),
    FILE_NAME VARCHAR(1000),
    RECORD_COUNT NUMBER(38,0),
    NOTES VARCHAR,
    CREATED_TS timestamp_ntz default current_timestamp(),

     CONSTRAINT foreign_key_client_id
        FOREIGN KEY (CLIENT_ID)
        REFERENCES CUSTOMER.MANAGEMENT.CLIENT(ID)
);

create or replace transient table CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS (
    CLIENT_ID NUMBER(32,0),
    BATCH_ID NUMBER(32, 0),
    RECORD_ID varchar,
    PREDICTED_GENDER varchar,
    REPORTABLE_GENDER varchar,
    CONFIDENCE_LEVEL varchar,
    MAX_PROBABILITY number(10,6),
    PROBABILITY_GAP number(10,6),
    MODEL_VERSION varchar,
    PROCESSED_TS timestamp_ntz
);