


CREATE OR REPLACE STORAGE INTEGRATION S3_INGEST_DATA_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::151562994023:role/snowflake_s3_ingest_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://inferlytica-snowflake-client-data-151562994023-us-east-1-an/uploads/', 's3://inferlytica-snowflake-provider-data-151562994023-us-east-1-an/uploads');


  DESC INTEGRATION S3_INGEST_DATA_INTEGRATION;
  --Update S3 IAM Role:
  --STORAGE_AWS_IAM_USER_ARN	String	arn:aws:iam::004878718171:user/64ll1000-s
  --STORAGE_AWS_EXTERNAL_ID	String	NVC23198_SFCRole=3_IjbJ/7NsEouUb0Sd7waRZNemO+k=


SELECT SYSTEM$VALIDATE_STORAGE_INTEGRATION(
  'S3_INGEST_DATA_INTEGRATION',
  's3://inferlytica-snowflake-client-data-151562994023-us-east-1-an/uploads/',
  'validate_list.txt',
  'list'
);

SELECT SYSTEM$VALIDATE_STORAGE_INTEGRATION(
  'S3_INGEST_DATA_INTEGRATION',
  's3://inferlytica-snowflake-provider-data-151562994023-us-east-1-an/uploads/',
  'validate_list.txt',
  'list'
);

SELECT SYSTEM$VALIDATE_STORAGE_INTEGRATION(
  'S3_INGEST_DATA_INTEGRATION',
  's3://inferlytica-snowflake-client-data-151562994023-us-east-1-an/uploads/',
  'updated_sample.csv',
  'read'
);

LIST @CUSTOMER.FILE_PROCESSING.CLIENT_DATA_STAGE PATTERN='.*updated_sample\\.csv';

CREATE OR REPLACE STAGE CUSTOMER.FILE_PROCESSING.CLIENT_DATA_STAGE
  URL = 's3://inferlytica-snowflake-client-data-151562994023-us-east-1-an/uploads/'
  STORAGE_INTEGRATION = S3_INGEST_DATA_INTEGRATION;

  CREATE OR REPLACE STAGE DATA_PROVIDER_SSA.RAW.PROVIDER_DATA_STAGE
  URL = 's3://inferlytica-snowflake-provider-data-151562994023-us-east-1-an/uploads/'
  STORAGE_INTEGRATION = S3_INGEST_DATA_INTEGRATION;

CREATE OR REPLACE STAGE DATA_PROVIDER_VOTER.RAW.PROVIDER_DATA_STAGE
  URL = 's3://inferlytica-snowflake-provider-data-151562994023-us-east-1-an/uploads/'
  STORAGE_INTEGRATION = S3_INGEST_DATA_INTEGRATION;

  SHOW FILE FORMATS;

LIST @CUSTOMER.FILE_PROCESSING.CLIENT_DATA_STAGE;

CREATE OR REPLACE PIPE CUSTOMER.FILE_PROCESSING.CLIENT_DATA_PIPE
  AUTO_INGEST = TRUE
  AS
  COPY INTO CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED
  FROM 
  (
     SELECT
        t.$1::VARCHAR AS RECORD_ID,
        t.$2::VARCHAR AS FIRST_NAME,
        t.$3::VARCHAR AS LAST_NAME,
        t.$4::VARCHAR AS ZIP,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER,
    METADATA$START_SCAN_TIME
    FROM @CUSTOMER.FILE_PROCESSING.CLIENT_DATA_STAGE AS t
  )
  FILE_FORMAT = CUSTOMER.FILE_PROCESSING.CUSTOMER_RAW_FORMAT;

DESC TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;
SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT;

  SHOW PIPES;
  --arn:aws:sqs:us-east-1:004878718171:sf-snowpipe-AIDAQCIWLKTNUANPOWPIV-Ym7zU2p6AX2KU7RyzdJdDg
SELECT SYSTEM$PIPE_STATUS('CUSTOMER.FILE_PROCESSING.CLIENT_DATA_PIPE');
DESC PIPE CUSTOMER.FILE_PROCESSING.CLIENT_DATA_PIPE;
--{"executionState":"RUNNING","pendingFileCount":0,"lastIngestedTimestamp":"2026-04-02T10:56:02.753Z","lastIngestedFilePath":"client_0922cdb9-f46e-4b15-a511-a902d2c913b2/batch_92fa1dff-56e9-4575-8ab0-18e63d4aa0dc/5c7303c0-02d7-42f6-9447-2b540aa8086b_444updated_sample.csv","notificationChannelName":"arn:aws:sqs:us-east-1:004878718171:sf-snowpipe-AIDAQCIWLKTNUANPOWPIV-Ym7zU2p6AX2KU7RyzdJdDg","numOutstandingMessagesOnChannel":1,"lastReceivedMessageTimestamp":"2026-04-02T10:56:02.591Z","lastForwardedMessageTimestamp":"2026-04-02T10:56:02.766Z","lastPulledFromChannelTimestamp":"2026-04-02T10:59:32.581Z","lastForwardedFilePath":"inferlytica-snowflake-client-data-151562994023-us-east-1-an/uploads/client_0922cdb9-f46e-4b15-a511-a902d2c913b2/batch_92fa1dff-56e9-4575-8ab0-18e63d4aa0dc/5c7303c0-02d7-42f6-9447-2b540aa8086b_444updated_sample.csv"}

--Message received
--2026-04-02 03:56:02.591

--Pipe copied data into preprocess
--2026-04-02 03:56:24.854	

--Stream kicked off task, (all data is already in RAW INPUT table)
--2026-04-02 03:56:26.682


USE DATABASE CUSTOMER;
SELECT *
FROM TABLE(
  CUSTOMER.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED',
    START_TIME => DATEADD('hour', -2, CURRENT_TIMESTAMP()),
    PIPE_NAME => 'CUSTOMER.FILE_PROCESSING.CLIENT_DATA_PIPE'
  )
)
ORDER BY LAST_LOAD_TIME DESC;

SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED;

--METADATA$FILENAME
--METADATA$START_SCAN_TIME


DROP STREAM CUSTOMER.PREPROCESSING.PERSON_INPUT_LANDING_STREAM;
--STREAM
CREATE OR REPLACE STREAM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED_LANDING_STREAM
ON TABLE CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED
APPEND_ONLY = TRUE;

--Task
CREATE OR REPLACE TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED_LANDING_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_FILE_TO_RAW();

ALTER TASK CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_DATA_UPLOAD_TASK RESUME;

DESC TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;
DESC TABLE CUSTOMER.RAW.PERSON_INPUT;
DESC TABLE CUSTOMER.MANAGEMENT.CLIENT;
DESC TABLE CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED;

SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED;

SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT;


SELECT *
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;

CALL CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_FILE_TO_RAW();


-- Proc
CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_FILE_TO_RAW()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN

    --PREP stream data
    CREATE OR REPLACE TEMP TABLE TMP_PERSON_INPUT_STREAM AS
    SELECT
        S.STORAGE_FILE_NAME,
        S.RECORD_ID,
        S.FIRST_NAME,
        S.LAST_NAME,
        S.ZIP,
        S.LOAD_TS,

        /* Parse ORG_ID from ...client_<ORG_ID>/... */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, 'client_([^/]+)', 1, 1, 'e', 1) AS APP_ORGANIZATION_ID,

        /* Parse BATCH_ID from .../batch_<BATCH_ID>/... */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, 'batch_([^/]+)', 1, 1, 'e', 1) AS APP_FILE_ID,

        /* Last path segment, e.g. abc123_myfile.csv */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, '[^/]+$') AS FILE_BASENAME,

        /* Remove UUID_ prefix from basename to get original source file name */
        REGEXP_REPLACE(
            REGEXP_SUBSTR(S.STORAGE_FILE_NAME, '[^/]+$'),
            '^[^_]+_',
            ''
        ) AS ORIGINAL_SOURCE_FILE_NAME
    FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED_LANDING_STREAM S;

     IF ((SELECT COUNT(*) FROM TMP_PERSON_INPUT_STREAM) = 0) THEN
        RETURN 'No rows in stream.';
    END IF;

    /* Insert one CLIENT_BATCH row per file */
    INSERT INTO CUSTOMER.FILE_PROCESSING.CLIENT_BATCH (
        CLIENT_ID,
        FILE_NAME,
        RECORD_COUNT,
        APP_FILE_ID
    )
    SELECT
        C.ID AS CLIENT_ID,
        T.ORIGINAL_SOURCE_FILE_NAME AS FILE_NAME,
        COUNT(*) AS RECORD_COUNT,
        T.APP_FILE_ID
    FROM TMP_PERSON_INPUT_STREAM T
    INNER JOIN CUSTOMER.MANAGEMENT.CLIENT C
        ON C.APP_ORGANIZATION_ID = T.APP_ORGANIZATION_ID
    LEFT JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        ON B.APP_FILE_ID = T.APP_FILE_ID
       AND B.CLIENT_ID = C.ID
    WHERE B.ID IS NULL
    GROUP BY
        C.ID,
        T.ORIGINAL_SOURCE_FILE_NAME,
        T.APP_FILE_ID;
    
    INSERT INTO CUSTOMER.RAW.PERSON_INPUT (
        CLIENT_ID,
        BATCH_ID,
        RECORD_ID,
        FIRST_NAME,
        LAST_NAME,
        ZIP,
        LOAD_TS
    )
    SELECT
        B.CLIENT_ID,
        B.ID AS BATCH_ID,
        T.RECORD_ID,
        T.FIRST_NAME,
        T.LAST_NAME,
        T.ZIP,
        T.LOAD_TS
    FROM TMP_PERSON_INPUT_STREAM T
    INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        ON B.APP_FILE_ID = T.APP_FILE_ID
    WHERE NOT EXISTS (
        SELECT 1
        FROM CUSTOMER.RAW.PERSON_INPUT R
        WHERE R.CLIENT_ID = B.CLIENT_ID
          AND R.BATCH_ID = B.ID
          AND R.RECORD_ID = T.RECORD_ID
    );

    UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        SET PROCESSED_TS = CURRENT_TIMESTAMP()
        WHERE EXISTS (
            SELECT 1
            FROM TMP_PERSON_INPUT_STREAM T
            WHERE T.APP_FILE_ID = B.APP_FILE_ID
        );
        
    DELETE FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED P
    WHERE EXISTS (
        SELECT 1
        FROM TMP_PERSON_INPUT_STREAM T
        WHERE T.STORAGE_FILE_NAME = P.STORAGE_FILE_NAME
          --AND T.SOURCE_ROW_NUMBER = P.FILE_RECORD_ROW_NUMBER
    );

    RETURN 'Processed ' || (SELECT COUNT(*) FROM TMP_PERSON_INPUT_STREAM) || ' stream rows.';
END;
$$;

DESC TABLE CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED;

DELETE FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED;

SELECT *
FROm CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;

SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT;

--
-- {
-- 	"Version": "2012-10-17",
-- 	"Statement": [
-- 		{
-- 			"Sid": "AllowBucketList",
-- 			"Effect": "Allow",
-- 			"Action": [
-- 				"s3:GetBucketLocation",
-- 				"s3:ListBucket"
-- 			],
-- 			"Resource": "arn:aws:s3:::inferlytica-snowflake-client-data"
-- 		},
-- 		{
-- 			"Sid": "AllowObjectRead",
-- 			"Effect": "Allow",
-- 			"Action": [
-- 				"s3:GetObject",
-- 				"s3:GetObjectVersion"
-- 			],
-- 			"Resource": "arn:aws:s3:::inferlytica-snowflake-client-data/uploads/*"
-- 		}
-- 	]
-- }