CREATE OR REPLACE TABLE CUSTOMER.MANAGEMENT.CLIENT 
(
    ID NUMBER(32,0) IDENTITY(1,1),
    ABBREVIATION VARCHAR(5),
    NAME VARCHAR(250),
    NOTES VARCHAR,
    CREATED_TS timestamp_ntz default current_timestamp(),
    CONSTRAINT primary_key_id PRIMARY KEY (ID)
    
)

;

ALTER TABLE CUSTOMER.MANAGEMENT.CLIENT 
ADD COLUMN MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT BOOLEAN DEFAULT FALSE;

ALTER TABLE CUSTOMER.MANAGEMENT.CLIENT 
ADD COLUMN  APP_ORGANIZATION_ID VARCHAR;

ALTER TABLE CUSTOMER.MANAGEMENT.CLIENT 
DROP COLUMN  CREDITS NUMBER (36,0);

SELECT *
FROM CUSTOMER.MANAGEMENT.CLIENT;

UPDATE CUSTOMER.MANAGEMENT.CLIENT 
SET APP_ORGANIZATION_ID = '0922cdb9-f46e-4b15-a511-a902d2c913b2';

UPDATE  CUSTOMER.MANAGEMENT.CLIENT 
SET MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT = TRUE;

DESC TABLE CUSTOMER.MANAGEMENT.CLIENT ;

ABBREVIATION	VARCHAR(5)
NAME	VARCHAR(250)
MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT	BOOLEAN