

SELECT *
FROM CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE;
CALL CUSTOMER.FILE_PROCESSING.APPROVE_BATCH_FOR_ENRICHMENT();

SELECT *
FROM CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE;


CREATE TEMP TABLE CUSTOMER.MANAGEMENT.TEMP_APP AS
SELECT *
FROM CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE;

DELETE
FROM CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE;

INSERT INTO CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE
SELECT * FROM CUSTOMER.MANAGEMENT.TEMP_APP;

--APPROVED
--1d96f728-bdc7-4554-8167-89cbd072b075	c23ff2a6-7855-451e-a18c-9f163c6f46d7
SELECT *
FROm CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_QUEUE;

SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED
WHERE CONTAINS(STORAGE_FILE_NAME, 'c23ff2a6-7855-451e-a18c-9f163c6f46d7');

UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
SET STORAGE_FILE_NAME = 'uploads/client_1d96f728-bdc7-4554-8167-89cbd072b075/batch_c23ff2a6-7855-451e-a18c-9f163c6f46d7/cee43fc8-76dd-4ce3-bb4b-adba873b1e8c_21if_test_updated_sample.csv'
WHERE APP_BATCH_ID = 'c23ff2a6-7855-451e-a18c-9f163c6f46d7';
--uploads/client_1d96f728-bdc7-4554-8167-89cbd072b075/batch_c1e3db13-28fc-49e7-8392-d8bc3f3482ae/b02c66b5-79b3-4d13-9446-e2084de28601_21if_test_updated_sample.csv

CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.APPROVE_BATCH_FOR_ENRICHMENT()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE 
    BATCH_COUNT NUMBER DEFAULT 0;
BEGIN

    --UPDATE TO PULL FROM APPROVAL STREAM (we just need app_org_id and app_batch_id to move on
    --CREATE OR REPLACE TEMP TABLE TMP_PERSON_INPUT_STREAM AS
   

    CREATE OR REPLACE TEMP TABLE TMP_APPROVAL_RESULTS AS
    SELECT
        APP_ORGANIZATION_ID,
        APP_BATCH_ID,
        STATUS,
        REQUESTED_CREDITS,
        APPROVED_CREDITS,
        DENIAL_REASON,
        DECISION_TS,
        CREATED_TS,
        UPDATED_TS
    FROM CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY APP_ORGANIZATION_ID, APP_BATCH_ID
        ORDER BY COALESCE(DECISION_TS, UPDATED_TS, CREATED_TS) DESC
    ) = 1;

    SELECT COUNT(*)
    INTO :BATCH_COUNT
    FROM TMP_APPROVAL_RESULTS;

    IF (:BATCH_COUNT = 0) THEN
        RETURN 'SUCCESS - PROCESSED 0 BATCH(ES)';
    END IF;

    MERGE INTO CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_QUEUE TGT
    USING TMP_APPROVAL_RESULTS SRC
        ON TGT.APP_ORGANIZATION_ID = SRC.APP_ORGANIZATION_ID
       AND TGT.APP_BATCH_ID = SRC.APP_BATCH_ID
    WHEN MATCHED THEN UPDATE SET
        TGT.STATUS = SRC.STATUS,
        TGT.REQUESTED_CREDITS = SRC.REQUESTED_CREDITS,
        TGT.APPROVED_CREDITS = SRC.APPROVED_CREDITS,
        TGT.DENIAL_REASON = SRC.DENIAL_REASON,
        TGT.DECISION_TS = SRC.DECISION_TS,
        TGT.UPDATED_TS = CURRENT_TIMESTAMP();


    
    -- THESE RECORDS TRIGGER ENRICHMENT (APPROVED TO PROCEED)
    INSERT INTO CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS (
        CLIENT_ID,
        BATCH_ID,
        APP_BATCH_ID,
        ENRICHMENT_TYPE,
        ENRICHMENT_TYPE_CODE,
        ENRICHMENT_STATUS
    )
    SELECT DISTINCT
        B.CLIENT_ID,
        B.ID AS BATCH_ID,
        T.APP_BATCH_ID AS APP_BATCH_ID,
        A.VALUE:label::VARCHAR AS ENRICHMENT_TYPE,
        A.VALUE:code::VARCHAR AS ENRICHMENT_TYPE_CODE,
        'PENDING' AS ENRICHMENT_STATUS
    FROM (
        SELECT DISTINCT
            APP_ORGANIZATION_ID,
            APP_BATCH_ID
        FROM TMP_APPROVAL_RESULTS
        WHERE STATUS = 'APPROVED'
    ) T
    INNER JOIN CUSTOMER.MANAGEMENT.CLIENT C
        ON C.APP_ORGANIZATION_ID = T.APP_ORGANIZATION_ID
    INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        ON B.CLIENT_ID = C.ID
       AND B.APP_BATCH_ID = T.APP_BATCH_ID
    INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_OUTPUT_CONFIGURATION CFG
        ON CFG.APP_ORGANIZATION_ID = T.APP_ORGANIZATION_ID
       AND CFG.APP_BATCH_ID = T.APP_BATCH_ID
    , LATERAL FLATTEN(INPUT => CFG.CONFIG_JSON:attributes) A
    WHERE A.VALUE:code IS NOT NULL
      AND NOT EXISTS (
          SELECT 1
          FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS S
          WHERE S.CLIENT_ID = B.CLIENT_ID
            AND S.BATCH_ID = B.ID
            AND S.APP_BATCH_ID = T.APP_BATCH_ID
            AND S.ENRICHMENT_TYPE_CODE = A.VALUE:code::VARCHAR
      );
      
    DELETE FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED P
    WHERE EXISTS (
        SELECT 1
        FROM TMP_APPROVAL_RESULTS T
        INNER JOIN CUSTOMER.MANAGEMENT.CLIENT C
            ON C.APP_ORGANIZATION_ID = T.APP_ORGANIZATION_ID
        INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
            ON B.CLIENT_ID = C.ID
           AND B.APP_BATCH_ID = T.APP_BATCH_ID
        WHERE B.STORAGE_FILE_NAME = P.STORAGE_FILE_NAME
          AND T.STATUS = 'APPROVED'
    );
    
    RETURN 'Processed ' || (SELECT COUNT(*) FROM TMP_APPROVAL_RESULTS) || ' stream rows.';
END;
$$;

SELECT *
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;
--NEED TO FIX to delete this raw data (line 130)
--join to batch and 
DESC TABLE CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED;
SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED;
--uploads/client_1d96f728-bdc7-4554-8167-89cbd072b075/batch_b6d2c6cf-b2bd-4491-b5b2-5bef63274f5f/dfa0d42f-baa1-46a8-ad87-9284c536cf1c_21if_test_updated_sample.csv

SELECT *
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;

SELECT *
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS;