CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.APPROVE_BATCH_FOR_ENRICHMENT()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN

    --UPDATE TO PULL FROM APPROVAL STREAM (we just need app_org_id and app_batch_id to move on
    CREATE OR REPLACE TEMP TABLE TMP_PERSON_INPUT_STREAM AS
    SELECT
        S.STORAGE_FILE_NAME,
        S.RECORD_ID,
        S.FIRST_NAME,
        S.LAST_NAME,
        S.ZIP,
        S.LOAD_TS,

        /* Parse ORG_ID from ...client_<ORG_ID>/... */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, 'client_([^/]+)', 1, 1, 'e', 1) AS APP_ORGANIZATION_ID,

        /* Parse BATCH_ID from .../batch_<BATCH_ID>/... */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, 'batch_([^/]+)', 1, 1, 'e', 1) AS APP_BATCH_ID,

        /* Last path segment, e.g. abc123_myfile.csv */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, '[^/]+$') AS FILE_BASENAME,

        /* Remove UUID_ prefix from basename to get original source file name */
        REGEXP_REPLACE(
            REGEXP_SUBSTR(S.STORAGE_FILE_NAME, '[^/]+$'),
            '^[^_]+_',
            ''
        ) AS ORIGINAL_SOURCE_FILE_NAME
    FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED_LANDING_STREAM S;


    
    -- THESE RECORDS TRIGGER ENRICHMENT
    INSERT INTO CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS (
        CLIENT_ID,
        BATCH_ID,
        APP_BATCH_ID,
        ENRICHMENT_TYPE,
        ENRICHMENT_TYPE_CODE,
        ENRICHMENT_STATUS
    )
    SELECT DISTINCT
        B.CLIENT_ID,
        B.ID AS BATCH_ID,
        T.APP_BATCH_ID AS APP_BATCH_ID,
        A.VALUE:label::VARCHAR AS ENRICHMENT_TYPE,
        A.VALUE:code::VARCHAR AS ENRICHMENT_TYPE_CODE,
        'PENDING' AS ENRICHMENT_STATUS
    FROM (
        SELECT DISTINCT
            APP_ORGANIZATION_ID,
            APP_BATCH_ID
        FROM TMP_PERSON_INPUT_STREAM
    ) T
    INNER JOIN CUSTOMER.MANAGEMENT.CLIENT C
        ON C.APP_ORGANIZATION_ID = T.APP_ORGANIZATION_ID
    INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        ON B.CLIENT_ID = C.ID
       AND B.APP_BATCH_ID = T.APP_BATCH_ID
    INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_OUTPUT_CONFIGURATION CFG
        ON CFG.APP_ORGANIZATION_ID = T.APP_ORGANIZATION_ID
       AND CFG.APP_BATCH_ID = T.APP_BATCH_ID
    , LATERAL FLATTEN(INPUT => CFG.CONFIG_JSON:attributes) A
    WHERE A.VALUE:code IS NOT NULL
      AND NOT EXISTS (
          SELECT 1
          FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS S
          WHERE S.CLIENT_ID = B.CLIENT_ID
            AND S.BATCH_ID = B.ID
            AND S.APP_BATCH_ID = T.APP_BATCH_ID
            AND S.ENRICHMENT_TYPE_CODE = A.VALUE:code::VARCHAR
      );
    

    UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        SET PROCESSED_TS = CURRENT_TIMESTAMP()
        WHERE EXISTS (
            SELECT 1
            FROM TMP_PERSON_INPUT_STREAM T
            WHERE T.APP_BATCH_ID = B.APP_BATCH_ID
        );
        
    DELETE FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED P
    WHERE EXISTS (
        SELECT 1
        FROM TMP_PERSON_INPUT_STREAM T
        WHERE T.STORAGE_FILE_NAME = P.STORAGE_FILE_NAME
          --AND T.SOURCE_ROW_NUMBER = P.FILE_RECORD_ROW_NUMBER
    );
    
    RETURN 'Processed ' || (SELECT COUNT(*) FROM TMP_PERSON_INPUT_STREAM) || ' stream rows.';
END;
$$;