CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.DELIVER_GENDER_RESULTS("MODEL_VERSION" VARCHAR DEFAULT 'v0.01')
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    BATCH_PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    BATCH_COUNT NUMBER DEFAULT 0;
BEGIN

    CREATE OR REPLACE TEMP TABLE BATCHES_TO_PROCESS AS
    SELECT DISTINCT
        b.CLIENT_ID,
        b.BATCH_ID
    FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE b
    INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH cb
        ON b.CLIENT_ID = cb.CLIENT_ID
       AND b.BATCH_ID = cb.ID
    WHERE cb.DELIVERY_COMPLETE_TS IS NULL;

    SELECT COUNT(*) INTO :BATCH_COUNT
    FROM BATCHES_TO_PROCESS;

    IF (:BATCH_COUNT = 0) THEN
        RETURN ''SUCCESS - NO UNPROCESSED BATCHES FOUND'';
    END IF;

    CREATE OR REPLACE TEMP TABLE BASELINE_TO_PROCESS AS
    SELECT b.*
    FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE b
    INNER JOIN BATCHES_TO_PROCESS p
        ON b.CLIENT_ID = p.CLIENT_ID
       AND b.BATCH_ID = p.BATCH_ID;

    MERGE INTO CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS tgt
    USING (
        SELECT
            CLIENT_ID,
            BATCH_ID,
            RECORD_ID,
            SSA_PREDICTED_GENDER AS PREDICTED_GENDER,
            SSA_REPORTABLE_GENDER AS REPORTABLE_GENDER,
            SSA_CONFIDENCE_LEVEL AS CONFIDENCE_LEVEL,
            SSA_MAX_PROBABILITY AS MAX_PROBABILITY,
            SSA_PROBABILITY_GAP AS PROBABILITY_GAP,
            :MODEL_VERSION AS MODEL_VERSION,
            LOAD_TS AS PROCESSED_TS
        FROM BASELINE_TO_PROCESS
    ) src
    ON tgt.CLIENT_ID = src.CLIENT_ID
   AND tgt.BATCH_ID = src.BATCH_ID
   AND tgt.RECORD_ID = src.RECORD_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.PREDICTED_GENDER = src.PREDICTED_GENDER,
        tgt.REPORTABLE_GENDER = src.REPORTABLE_GENDER,
        tgt.CONFIDENCE_LEVEL = src.CONFIDENCE_LEVEL,
        tgt.MAX_PROBABILITY = src.MAX_PROBABILITY,
        tgt.PROBABILITY_GAP = src.PROBABILITY_GAP,
        tgt.MODEL_VERSION = src.MODEL_VERSION,
        tgt.PROCESSED_TS = src.PROCESSED_TS
    WHEN NOT MATCHED THEN INSERT (
        CLIENT_ID,
        BATCH_ID,
        RECORD_ID,
        PREDICTED_GENDER,
        REPORTABLE_GENDER,
        CONFIDENCE_LEVEL,
        MAX_PROBABILITY,
        PROBABILITY_GAP,
        MODEL_VERSION,
        PROCESSED_TS
    )
    VALUES (
        src.CLIENT_ID,
        src.BATCH_ID,
        src.RECORD_ID,
        src.PREDICTED_GENDER,
        src.REPORTABLE_GENDER,
        src.CONFIDENCE_LEVEL,
        src.MAX_PROBABILITY,
        src.PROBABILITY_GAP,
        src.MODEL_VERSION,
        src.PROCESSED_TS
    );

    MERGE INTO CUSTOMER.ANALYTICS.BATCH_GENDER_SUMMARY tgt
    USING (
        SELECT
            CLIENT_ID,
            BATCH_ID,
            :MODEL_VERSION AS MODEL_VERSION,
            COUNT(*) AS TOTAL_RECORDS,
            SUM(CASE WHEN FIRST_NAME_MISSING_FLAG = 0 THEN 1 ELSE 0 END) AS USABLE_FIRST_NAME_RECORDS,
            SUM(CASE WHEN SSA_LOOKUP_MATCH_FLAG = 1 THEN 1 ELSE 0 END) AS SSA_LOOKUP_MATCH_RECORDS,
            CASE
                WHEN COUNT(*) = 0 THEN 0
                ELSE SUM(CASE WHEN SSA_LOOKUP_MATCH_FLAG = 1 THEN 1 ELSE 0 END) / COUNT(*)
            END AS SSA_LOOKUP_MATCH_RATE,
            SUM(CASE WHEN SSA_CONFIDENCE_LEVEL = ''HIGH'' THEN 1 ELSE 0 END) AS HIGH_CONFIDENCE_RECORDS,
            SUM(CASE WHEN SSA_CONFIDENCE_LEVEL = ''MEDIUM'' THEN 1 ELSE 0 END) AS MEDIUM_CONFIDENCE_RECORDS,
            SUM(CASE WHEN SSA_CONFIDENCE_LEVEL = ''LOW'' THEN 1 ELSE 0 END) AS LOW_CONFIDENCE_RECORDS,
            SUM(CASE WHEN SSA_CONFIDENCE_LEVEL = ''AMBIGUOUS'' THEN 1 ELSE 0 END) AS AMBIGUOUS_RECORDS,
            SUM(CASE WHEN SSA_REPORTABLE_GENDER = ''M'' THEN 1 ELSE 0 END) AS REPORTABLE_M_RECORDS,
            SUM(CASE WHEN SSA_REPORTABLE_GENDER = ''F'' THEN 1 ELSE 0 END) AS REPORTABLE_F_RECORDS,
            SUM(CASE WHEN SSA_REPORTABLE_GENDER = ''U'' THEN 1 ELSE 0 END) AS REPORTABLE_U_RECORDS,
            :BATCH_PROCESSED_TS AS PROCESSED_TS
        FROM BASELINE_TO_PROCESS
        GROUP BY
            CLIENT_ID,
            BATCH_ID
    ) src
    ON tgt.CLIENT_ID = src.CLIENT_ID
   AND tgt.BATCH_ID = src.BATCH_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.MODEL_VERSION = src.MODEL_VERSION,
        tgt.TOTAL_RECORDS = src.TOTAL_RECORDS,
        tgt.USABLE_FIRST_NAME_RECORDS = src.USABLE_FIRST_NAME_RECORDS,
        tgt.SSA_LOOKUP_MATCH_RECORDS = src.SSA_LOOKUP_MATCH_RECORDS,
        tgt.SSA_LOOKUP_MATCH_RATE = src.SSA_LOOKUP_MATCH_RATE,
        tgt.HIGH_CONFIDENCE_RECORDS = src.HIGH_CONFIDENCE_RECORDS,
        tgt.MEDIUM_CONFIDENCE_RECORDS = src.MEDIUM_CONFIDENCE_RECORDS,
        tgt.LOW_CONFIDENCE_RECORDS = src.LOW_CONFIDENCE_RECORDS,
        tgt.AMBIGUOUS_RECORDS = src.AMBIGUOUS_RECORDS,
        tgt.REPORTABLE_M_RECORDS = src.REPORTABLE_M_RECORDS,
        tgt.REPORTABLE_F_RECORDS = src.REPORTABLE_F_RECORDS,
        tgt.REPORTABLE_U_RECORDS = src.REPORTABLE_U_RECORDS,
        tgt.PROCESSED_TS = src.PROCESSED_TS
    WHEN NOT MATCHED THEN INSERT (
        CLIENT_ID,
        BATCH_ID,
        MODEL_VERSION,
        TOTAL_RECORDS,
        USABLE_FIRST_NAME_RECORDS,
        SSA_LOOKUP_MATCH_RECORDS,
        SSA_LOOKUP_MATCH_RATE,
        HIGH_CONFIDENCE_RECORDS,
        MEDIUM_CONFIDENCE_RECORDS,
        LOW_CONFIDENCE_RECORDS,
        AMBIGUOUS_RECORDS,
        REPORTABLE_M_RECORDS,
        REPORTABLE_F_RECORDS,
        REPORTABLE_U_RECORDS,
        PROCESSED_TS
    )
    VALUES (
        src.CLIENT_ID,
        src.BATCH_ID,
        src.MODEL_VERSION,
        src.TOTAL_RECORDS,
        src.USABLE_FIRST_NAME_RECORDS,
        src.SSA_LOOKUP_MATCH_RECORDS,
        src.SSA_LOOKUP_MATCH_RATE,
        src.HIGH_CONFIDENCE_RECORDS,
        src.MEDIUM_CONFIDENCE_RECORDS,
        src.LOW_CONFIDENCE_RECORDS,
        src.AMBIGUOUS_RECORDS,
        src.REPORTABLE_M_RECORDS,
        src.REPORTABLE_F_RECORDS,
        src.REPORTABLE_U_RECORDS,
        src.PROCESSED_TS
    );

    MERGE INTO INFERLYTICA.CLIENT_MODEL_IMPROVEMENT.GENDER_OUTPUT_MODEL_RESULTS tgt
    USING (
        SELECT
            b.CLIENT_ID,
            b.BATCH_ID,
            b.RECORD_ID,
            b.FIRST_NAME_RAW,
            b.FIRST_NAME_CLEAN,
            b.LAST_NAME_RAW,
            b.LAST_NAME_CLEAN,
            b.ZIP_RAW,
            b.ZIP5,
            b.SSA_MALE_PROBABILITY,
            b.SSA_FEMALE_PROBABILITY,
            b.SSA_CONFIDENCE_LEVEL,
            b.SSA_LOOKUP_MATCH_FLAG,
            b.SSA_PREDICTED_GENDER,
            b.SSA_REPORTABLE_GENDER,
            :MODEL_VERSION AS MODEL_VERSION
        FROM BASELINE_TO_PROCESS b
        INNER JOIN CUSTOMER.MANAGEMENT.CLIENT c
            ON b.CLIENT_ID = c.ID
        WHERE c.MODEL_IMPROVEMENT_PROGRAM_PARTICIPANT = TRUE
    ) src
    ON tgt.CLIENT_ID = src.CLIENT_ID
   AND tgt.BATCH_ID = src.BATCH_ID
   AND tgt.RECORD_ID = src.RECORD_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.FIRST_NAME_RAW = src.FIRST_NAME_RAW,
        tgt.FIRST_NAME_CLEAN = src.FIRST_NAME_CLEAN,
        tgt.LAST_NAME_RAW = src.LAST_NAME_RAW,
        tgt.LAST_NAME_CLEAN = src.LAST_NAME_CLEAN,
        tgt.ZIP_RAW = src.ZIP_RAW,
        tgt.ZIP5 = src.ZIP5,
        tgt.SSA_MALE_PROBABILITY = src.SSA_MALE_PROBABILITY,
        tgt.SSA_FEMALE_PROBABILITY = src.SSA_FEMALE_PROBABILITY,
        tgt.SSA_CONFIDENCE_LEVEL = src.SSA_CONFIDENCE_LEVEL,
        tgt.SSA_LOOKUP_MATCH_FLAG = src.SSA_LOOKUP_MATCH_FLAG,
        tgt.SSA_PREDICTED_GENDER = src.SSA_PREDICTED_GENDER,
        tgt.SSA_REPORTABLE_GENDER = src.SSA_REPORTABLE_GENDER,
        tgt.MODEL_VERSION = src.MODEL_VERSION
    WHEN NOT MATCHED THEN INSERT (
        CLIENT_ID,
        BATCH_ID,
        RECORD_ID,
        FIRST_NAME_RAW,
        FIRST_NAME_CLEAN,
        LAST_NAME_RAW,
        LAST_NAME_CLEAN,
        ZIP_RAW,
        ZIP5,
        SSA_MALE_PROBABILITY,
        SSA_FEMALE_PROBABILITY,
        SSA_CONFIDENCE_LEVEL,
        SSA_LOOKUP_MATCH_FLAG,
        SSA_PREDICTED_GENDER,
        SSA_REPORTABLE_GENDER,
        MODEL_VERSION
    )
    VALUES (
        src.CLIENT_ID,
        src.BATCH_ID,
        src.RECORD_ID,
        src.FIRST_NAME_RAW,
        src.FIRST_NAME_CLEAN,
        src.LAST_NAME_RAW,
        src.LAST_NAME_CLEAN,
        src.ZIP_RAW,
        src.ZIP5,
        src.SSA_MALE_PROBABILITY,
        src.SSA_FEMALE_PROBABILITY,
        src.SSA_CONFIDENCE_LEVEL,
        src.SSA_LOOKUP_MATCH_FLAG,
        src.SSA_PREDICTED_GENDER,
        src.SSA_REPORTABLE_GENDER,
        src.MODEL_VERSION
    );

    UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH cb
    SET DELIVERY_COMPLETE_TS = :BATCH_PROCESSED_TS
    WHERE EXISTS (
        SELECT 1
        FROM BATCHES_TO_PROCESS p
        WHERE p.CLIENT_ID = cb.CLIENT_ID
          AND p.BATCH_ID = cb.ID
    );

    MERGE INTO CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_NOTIFICATIONS tgt
    USING (
        SELECT
            p.CLIENT_ID,
            p.BATCH_ID,
            cb.APP_FILE_ID,
            c.APP_ORGANIZATION_ID,
            TO_JSON(
                OBJECT_CONSTRUCT(
                    ''organization_id'', c.APP_ORGANIZATION_ID,
                    ''batch_id'', cb.APP_FILE_ID,
                    ''delivery_status'', ''READY'',
                    ''delivery_status_updated_at'', CURRENT_TIMESTAMP()
                )
            ) AS PAYLOAD,
            ''DELIVERY_STATUS_UPDATED'' AS EVENT_TYPE,
            ''READY'' AS STATUS,
            0 AS ATTEMPT_COUNT,
            NULL AS LAST_ATTEMPT_TS,
            NULL AS LAST_ERROR,
            CURRENT_TIMESTAMP() AS CREATED_TS,
            NULL AS PROCESSED_TS
        FROM BATCHES_TO_PROCESS p
        INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH cb
            ON p.CLIENT_ID = cb.CLIENT_ID
           AND p.BATCH_ID = cb.ID
        INNER JOIN CUSTOMER.MANAGEMENT.CLIENT c
            ON p.CLIENT_ID = c.ID
    ) src
    ON tgt.CLIENT_ID = src.CLIENT_ID
    AND tgt.BATCH_ID = src.BATCH_ID
    AND tgt.EVENT_TYPE = src.EVENT_TYPE
    AND tgt.PROCESSED_TS IS NULL
    WHEN MATCHED THEN UPDATE SET
        tgt.APP_FILE_ID = src.APP_FILE_ID,
        tgt.APP_ORGANIZATION_ID = src.APP_ORGANIZATION_ID,
        tgt.PAYLOAD = src.PAYLOAD,
        tgt.STATUS = src.STATUS
    WHEN NOT MATCHED THEN INSERT
    (
        CLIENT_ID,
        BATCH_ID,
        APP_FILE_ID,
        APP_ORGANIZATION_ID,
        PAYLOAD,
        EVENT_TYPE,
        STATUS,
        ATTEMPT_COUNT,
        LAST_ATTEMPT_TS,
        LAST_ERROR,
        CREATED_TS,
        PROCESSED_TS
    )
    VALUES
    (
        src.CLIENT_ID,
        src.BATCH_ID,
        src.APP_FILE_ID,
        src.APP_ORGANIZATION_ID,
        src.PAYLOAD,
        src.EVENT_TYPE,
        src.STATUS,
        src.ATTEMPT_COUNT,
        src.LAST_ATTEMPT_TS,
        src.LAST_ERROR,
        src.CREATED_TS,
        src.PROCESSED_TS
    );

    DELETE FROM CUSTOMER.RAW.PERSON_INPUT r
    WHERE EXISTS (
        SELECT 1
        FROM BATCHES_TO_PROCESS p
        WHERE p.CLIENT_ID = r.CLIENT_ID
          AND p.BATCH_ID = r.BATCH_ID
    );

    ALTER DYNAMIC TABLE CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE REFRESH;

    RETURN ''SUCCESS - PROCESSED '' || :BATCH_COUNT || '' BATCH(ES)'';
END;
';