CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.ENRICH_WITH_AGE_COLLAPSED("MODEL_VERSION" VARCHAR DEFAULT 'v0.01')
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    BATCH_PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
    BATCH_COUNT NUMBER DEFAULT 0;
BEGIN

   

    RETURN ''SUCCESS - PROCESSED 00000 BATCH(ES)'';
END;
';