DESC TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_QUEUE;
name	type	kind	null?	default
APP_ORGANIZATION_ID	VARCHAR(16777216)	COLUMN	N	
APP_BATCH_ID	VARCHAR(16777216)	COLUMN	N	
QUEUED_TS	TIMESTAMP_NTZ(9)	COLUMN	N	CURRENT_TIMESTAMP()
PROCESSING_STATUS	VARCHAR(16777216)	COLUMN	N	'PENDING'
PROCESSING_STARTED_TS	TIMESTAMP_NTZ(9)	COLUMN	Y	
PROCESSED_TS	TIMESTAMP_NTZ(9)	COLUMN	Y	
ERROR_MESSAGE	VARCHAR(16777216)	COLUMN	Y	
CREATED_TS	TIMESTAMP_NTZ(9)	COLUMN	N	CURRENT_TIMESTAMP()
UPDATED_TS	TIMESTAMP_NTZ(9)	COLUMN	N	CURRENT_TIMESTAMP();

DESC TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;
--DOWNLOAD_OBJECT_KEY -- to populate with S3 object key
--APP_BATCH_ID --to link to app batch id
--CLIENT_ID (links to CUSTOMER.MANAGEMENT.CLIENT.ID to get the APP_ORGANIZATION_ID)

DESC TABLE CUSTOMER.MANAGEMENT.CLIENT;

CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.PREPARE_DOWNLOAD()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$

BEGIN

-- on demand downloads
    CREATE OR REPLACE TEMP TABLE TMP_CLIENT_BATCH_DOWNLOAD_QUEUE_STREAM AS
    SELECT DISTINCT
        S.APP_ORGANIZATION_ID,
        S.APP_BATCH_ID,
        S.QUEUED_TS
    FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_QUEUE_STREAM S
    WHERE S.PROCESSING_STATUS = 'PENDING';

    

    RETURN 'Processed ' || (SELECT COUNT(*) FROM TMP_CLIENT_BATCH_DOWNLOAD_QUEUE_STREAM) || ' stream rows.';
END;
$$;