CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.START_ENRICHMENT_PROCESS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    V_ROW_COUNT NUMBER DEFAULT 0;
    V_HAS_GNDRPR BOOLEAN DEFAULT FALSE;
    V_HAS_AGEXPD BOOLEAN DEFAULT FALSE;
    V_HAS_AGCLPS BOOLEAN DEFAULT FALSE;

    RS_GNDRPR RESULTSET;
    RS_AGEXPD RESULTSET;
    RS_AGCLPS RESULTSET;
BEGIN

    CREATE OR REPLACE TEMP TABLE TMP_ENRICHMENT_STATUS_STREAM AS
    SELECT DISTINCT
        S.CLIENT_ID,
        S.BATCH_ID,
        S.APP_FILE_ID,
        S.ENRICHMENT_TYPE,
        S.ENRICHMENT_TYPE_CODE
    FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS_STREAM S
    WHERE S.ENRICHMENT_STATUS = 'PENDING';

    SELECT COUNT(*) INTO :V_ROW_COUNT
    FROM TMP_ENRICHMENT_STATUS_STREAM;

    IF (V_ROW_COUNT = 0) THEN
        RETURN 'No pending enrichment status rows in stream.';
    END IF;

    UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS T
    SET
        ENRICHMENT_STATUS = 'RUNNING',
        STARTED_TS = COALESCE(T.STARTED_TS, CURRENT_TIMESTAMP()),
        UPDATED_TS = CURRENT_TIMESTAMP(),
        ERROR_MESSAGE = NULL
    WHERE EXISTS (
        SELECT 1
        FROM TMP_ENRICHMENT_STATUS_STREAM S
        WHERE S.CLIENT_ID = T.CLIENT_ID
          AND S.BATCH_ID = T.BATCH_ID
          AND S.APP_FILE_ID = T.APP_FILE_ID
          AND S.ENRICHMENT_TYPE_CODE = T.ENRICHMENT_TYPE_CODE
    )
      AND T.ENRICHMENT_STATUS = 'PENDING';

    UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS T
    SET
        ENRICHMENT_STATUS = 'FAILED',
        ERROR_MESSAGE = 'Unsupported enrichment type code.',
        UPDATED_TS = CURRENT_TIMESTAMP()
    WHERE EXISTS (
        SELECT 1
        FROM TMP_ENRICHMENT_STATUS_STREAM S
        WHERE S.CLIENT_ID = T.CLIENT_ID
          AND S.BATCH_ID = T.BATCH_ID
          AND S.APP_FILE_ID = T.APP_FILE_ID
          AND S.ENRICHMENT_TYPE_CODE = T.ENRICHMENT_TYPE_CODE
          AND S.ENRICHMENT_TYPE_CODE NOT IN (
              SELECT CODE
              FROM INFERLYTICA.CONFIGURATION.ENRICHMENT_ATTRIBUTE
          )
    )
      AND T.ENRICHMENT_STATUS = 'RUNNING';

       SELECT COUNT(*) > 0 INTO :V_HAS_GNDRPR
    FROM TMP_ENRICHMENT_STATUS_STREAM
    WHERE ENRICHMENT_TYPE_CODE = 'GNDRPR';

    SELECT COUNT(*) > 0 INTO :V_HAS_AGEXPD
    FROM TMP_ENRICHMENT_STATUS_STREAM
    WHERE ENRICHMENT_TYPE_CODE = 'AGEXPD';

    SELECT COUNT(*) > 0 INTO :V_HAS_AGCLPS
    FROM TMP_ENRICHMENT_STATUS_STREAM
    WHERE ENRICHMENT_TYPE_CODE = 'AGCLPS';

    IF (V_HAS_GNDRPR) THEN
        RS_GNDRPR := ASYNC (CALL CUSTOMER.FILE_PROCESSING.ENRICH_WITH_GENDER());
    END IF;

    IF (V_HAS_AGEXPD) THEN
        RS_AGEXPD := ASYNC (CALL CUSTOMER.FILE_PROCESSING.ENRICH_WITH_AGE_EXPANDED());
    END IF;

    IF (V_HAS_AGCLPS) THEN
       RS_AGCLPS := ASYNC (CALL CUSTOMER.FILE_PROCESSING.ENRICH_WITH_AGE_COLLAPSED());
    END IF;

    AWAIT ALL;

    RETURN 'Started enrichment processing for '
        || V_ROW_COUNT
        || ' pending status row(s).';

EXCEPTION
    WHEN STATEMENT_ERROR THEN
        UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS T
        SET
            ENRICHMENT_STATUS = 'FAILED',
            ERROR_MESSAGE = SQLERRM,
            UPDATED_TS = CURRENT_TIMESTAMP()
        WHERE EXISTS (
            SELECT 1
            FROM TMP_ENRICHMENT_STATUS_STREAM S
            WHERE S.CLIENT_ID = T.CLIENT_ID
              AND S.BATCH_ID = T.BATCH_ID
              AND S.APP_FILE_ID = T.APP_FILE_ID
              AND S.ENRICHMENT_TYPE_CODE = T.ENRICHMENT_TYPE_CODE
        )
          AND T.ENRICHMENT_STATUS = 'RUNNING'
          AND T.COMPLETED_TS IS NULL;

        RETURN 'Failed starting enrichment process: ' || SQLERRM;
END;
$$;