--CALL CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_FILE_TO_RAW();

CREATE OR REPLACE PROCEDURE CUSTOMER.FILE_PROCESSING.PROCESS_CLIENT_FILE_TO_RAW()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN

    --PREP stream data
    CREATE OR REPLACE TEMP TABLE TMP_PERSON_INPUT_STREAM AS
    SELECT
        S.STORAGE_FILE_NAME,
        S.RECORD_ID,
        S.FIRST_NAME,
        S.LAST_NAME,
        S.ZIP,
        S.LOAD_TS,

        /* Parse ORG_ID from ...client_<ORG_ID>/... */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, 'client_([^/]+)', 1, 1, 'e', 1) AS APP_ORGANIZATION_ID,

        /* Parse BATCH_ID from .../batch_<BATCH_ID>/... */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, 'batch_([^/]+)', 1, 1, 'e', 1) AS APP_FILE_ID,

        /* Last path segment, e.g. abc123_myfile.csv */
        REGEXP_SUBSTR(S.STORAGE_FILE_NAME, '[^/]+$') AS FILE_BASENAME,

        /* Remove UUID_ prefix from basename to get original source file name */
        REGEXP_REPLACE(
            REGEXP_SUBSTR(S.STORAGE_FILE_NAME, '[^/]+$'),
            '^[^_]+_',
            ''
        ) AS ORIGINAL_SOURCE_FILE_NAME
    FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED_LANDING_STREAM S;

     IF ((SELECT COUNT(*) FROM TMP_PERSON_INPUT_STREAM) = 0) THEN
        RETURN 'No rows in stream.';
    END IF;

    /* Insert one CLIENT_BATCH row per file */
    INSERT INTO CUSTOMER.FILE_PROCESSING.CLIENT_BATCH (
        CLIENT_ID,
        FILE_NAME,
        RECORD_COUNT,
        APP_FILE_ID
    )
    SELECT
        C.ID AS CLIENT_ID,
        T.ORIGINAL_SOURCE_FILE_NAME AS FILE_NAME,
        COUNT(*) AS RECORD_COUNT,
        T.APP_FILE_ID
    FROM TMP_PERSON_INPUT_STREAM T
    INNER JOIN CUSTOMER.MANAGEMENT.CLIENT C
        ON C.APP_ORGANIZATION_ID = T.APP_ORGANIZATION_ID
    LEFT JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        ON B.APP_FILE_ID = T.APP_FILE_ID
       AND B.CLIENT_ID = C.ID
    WHERE B.ID IS NULL
    GROUP BY
        C.ID,
        T.ORIGINAL_SOURCE_FILE_NAME,
        T.APP_FILE_ID;
    
    INSERT INTO CUSTOMER.RAW.PERSON_INPUT (
        CLIENT_ID,
        BATCH_ID,
        RECORD_ID,
        FIRST_NAME,
        LAST_NAME,
        ZIP,
        LOAD_TS
    )
    SELECT
        B.CLIENT_ID,
        B.ID AS BATCH_ID,
        T.RECORD_ID,
        T.FIRST_NAME,
        T.LAST_NAME,
        T.ZIP,
        T.LOAD_TS
    FROM TMP_PERSON_INPUT_STREAM T
    INNER JOIN CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        ON B.APP_FILE_ID = T.APP_FILE_ID
    WHERE NOT EXISTS (
        SELECT 1
        FROM CUSTOMER.RAW.PERSON_INPUT R
        WHERE R.CLIENT_ID = B.CLIENT_ID
          AND R.BATCH_ID = B.ID
          AND R.RECORD_ID = T.RECORD_ID
    );

    UPDATE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH B
        SET PROCESSED_TS = CURRENT_TIMESTAMP()
        WHERE EXISTS (
            SELECT 1
            FROM TMP_PERSON_INPUT_STREAM T
            WHERE T.APP_FILE_ID = B.APP_FILE_ID
        );
        
    DELETE FROM CUSTOMER.RAW.PERSON_INPUT_PREPROCESSED P
    WHERE EXISTS (
        SELECT 1
        FROM TMP_PERSON_INPUT_STREAM T
        WHERE T.STORAGE_FILE_NAME = P.STORAGE_FILE_NAME
          --AND T.SOURCE_ROW_NUMBER = P.FILE_RECORD_ROW_NUMBER
    );

    RETURN 'Processed ' || (SELECT COUNT(*) FROM TMP_PERSON_INPUT_STREAM) || ' stream rows.';
END;
$$;