CREATE OR REPLACE PROCEDURE CUSTOMER.MANAGEMENT.UPDATE_APPROVAL_REQUEST()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
'
DECLARE BATCH_COUNT NUMBER DEFAULT 0;

BEGIN

   

    RETURN ''SUCCESS - PROCESSED '' || :BATCH_COUNT || '' BATCH(ES)'';
END;
';