CREATE OR REPLACE TRANSIENT DYNAMIC TABLE DATA_PROVIDER_VOTER.STAGE.STATE_WA_VOTER_REGISTRATION (
    STATE_VOTER_ID,           
    NAME_SUFFIX,            
    FIRST_NAME,            
    MIDDLE_NAME,            
    LAST_NAME,            
    GENDER, 
    BIRTH_YEAR,               
    REGISTRATION_ZIP_CODE,
    REGISTRATION_STATE,
    MAILING_ZIP_CODE, 
    MAILING_STATE,
    LOADED_TS
) target_lag = 'DOWNSTREAM' refresh_mode = INCREMENTAL initialize = ON_CREATE warehouse = COMPUTE_WH
as
select
    STATE_VOTER_ID AS STATE_VOTER_ID,
    NAME_SUFFIX AS NAME_SUFFIX,
    INFERLYTICA.UTILITY.NORMALIZE_NAME(FIRST_NAME) as FIRST_NAME,
    INFERLYTICA.UTILITY.NORMALIZE_NAME(MIDDLE_NAME) as MIDDLE_NAME,
    INFERLYTICA.UTILITY.NORMALIZE_NAME(LAST_NAME) as LAST_NAME,
    INFERLYTICA.UTILITY.NORMALIZE_GENDER(GENDER) as GENDER,
    BIRTH_YEAR AS BIRTH_YEAR,
    INFERLYTICA.UTILITY.NORMALIZE_ZIP5(REGISTRATION_ZIP_CODE) as ZIP5_REGISTRATION,
    REGISTRATION_STATE AS REGISTRATION_STATE,
    INFERLYTICA.UTILITY.NORMALIZE_ZIP5(MAILING_ZIP_CODE) as ZIP5_MAILING,
    MAILING_STATE as MAILING_STATE,
    LOADED_TS AS LOADED_TS
from DATA_PROVIDER_VOTER.RAW.STATE_WA_VOTER_REGISTRATION
where INFERLYTICA.UTILITY.NORMALIZE_NAME(FIRST_NAME) is not null
AND INFERLYTICA.UTILITY.NORMALIZE_GENDER(GENDER) IN ('M', 'F');