CREATE OR REPLACE TASK CUSTOMER.MANAGEMENT.TRIGGER_UPDATE_APPROVAL_REQUEST_TASK
  USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS = 10
  SERVERLESS_TASK_MAX_STATEMENT_SIZE = XSMALL
  TARGET_COMPLETION_INTERVAL = '15 MINUTES'
  WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE_STREAM')
AS
CALL CUSTOMER.FILE_PROCESSING.APPROVE_BATCH_FOR_ENRICHMENT();

ALTER TASK CUSTOMER.MANAGEMENT.TRIGGER_UPDATE_APPROVAL_REQUEST_TASK RESUME;

SELECT SYSTEM$STREAM_HAS_DATA('CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE_STREAM');

SELECT *
FROM TABLE(
  CUSTOMER.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TRIGGER_UPDATE_APPROVAL_REQUEST_TASK',
    RESULT_LIMIT => 50
  )
)
ORDER BY SCHEDULED_TIME DESC;

SELECT *
FROM CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE
WHERE APP_BATCH_ID  IN
(
'dba6bb59-1f8a-47d0-b835-91dd73c9b684',
'b6d2c6cf-b2bd-4491-b5b2-5bef63274f5f'
);

SQL compilation error:
Unknown user-defined function CUSTOMER.FILE_PROCESSING.APPROVE_BATCH_FOR_ENRICHMENT.

--Uncaught exception of type 'STATEMENT_ERROR' on line 35 at position 4 : SQL compilation error:
Object 'CUSTOMER.FILE_PROCESSING.CREDIT_APPROVAL_QUEUE' does not exist or not authorized.
