SELECT *
FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE;

SELECT *
FROM CUSTOMER.RAW.PERSON_INPUT;

SELECT *
FROM CUSTOMER.STAGE.PERSON_INPUT_CLEAN;

SELECT SSA_CONFIDENCE_LEVEL, COUNT(*)
FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE
GROUP BY SSA_CONFIDENCE_LEVEL;

SELECT FIRST_NAME_RAW, FIRST_NAME_CLEAN, SSA_IS_RARE_NAME, SSA_CONFIDENCE_LEVEL, SSA_FEMALE_PROBABILITY, SSA_MALE_PROBABILITY ,SSA_PREDICTED_GENDER, SSA_REPORTABLE_GENDER
FROM CUSTOMER.ANALYTICS.PERSON_INPUT_GENDER_BASELINE
WHERE SSA_CONFIDENCE_LEVEL <> 'HIGH';

SELECT *
FROM DATA_PROVIDER_SSA.ANALYTICS.FIRST_NAME_GENDER_QUANTITY_LOOKUP
WHERE FIRST_NAME ILIKE 'forrest';

SELECT *
FROM DATA_PROVIDER_SSA.STAGE.FIRST_NAME_GENDER_QUANTITY_YEAR
WHERE FIRST_NAME ILIKE 'forrest'
ORDER BY YEAR;
