
SELECT 
FROM DATA_PROVIDER_SSA.RAW.FIRST_NAME_GENDER_QUANTITY_YEAR
GROUP BY GENDER;

SELECT FIRST_NAME, GENDER, YEAR, QUANTITY
FROM DATA_PROVIDER_SSA.RAW.FIRST_NAME_GENDER_QUANTITY_YEAR
QUALIFY ROW_NUMBER() OVER (PARTITION BY GENDER, YEAR ORDER BY QUANTITY ASC) = 1
ORDER BY YEAR, GENDER;


SELECT FIRST_NAME, GENDER, YEAR, QUANTITY
FROM DATA_PROVIDER_SSA.RAW.FIRST_NAME_GENDER_QUANTITY_YEAR
WHERE FIRST_NAME = 'charley' OR FIRST_NAME = 'charlie'
ORDER BY YEAR, GENDER;

SELECT FIRST_NAME, GENDER, YEAR, QUANTITY
FROM DATA_PROVIDER_SSA.RAW.FIRST_NAME_GENDER_QUANTITY_YEAR
WHERE FIRST_NAME = 'kerri';-- AND GENDER = 'F';

SELECT *
FROM DATA_PROVIDER_SSA.RAW.FIRST_NAME_GENDER_QUANTITY_YEAR;