CREATE OR REPLACE TRANSIENT TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_NOTIFICATIONS
(
    ID NUMBER(32,0) IDENTITY(1,1),
    CLIENT_ID NUMBER(32,0) NOT NULL,
    BATCH_ID NUMBER(32, 0) NOT NULL,
    APP_FILE_ID VARCHAR NOT NULL,
    APP_ORGANIZATION_ID VARCHAR NOT NULL,
    PAYLOAD VARCHAR,
    EVENT_TYPE VARCHAR,
    STATUS VARCHAR,
    ATTEMPT_COUNT VARCHAR,
    LAST_ATTEMPT_TS timestamp_ntz,
    LAST_ERROR VARCHAR,
    CREATED_TS timestamp_ntz default current_timestamp(),
    PROCESSED_TS timestamp_ntz

);


    CONSTRAINT foreign_key_batch_id
        FOREIGN KEY (BATCH_ID)
        REFERENCES CUSTOMER.FILE_PROCESSING.CLIENT_BATCH(ID)


        
     CONSTRAINT foreign_key_client_id
        FOREIGN KEY (CLIENT_ID)
        REFERENCES CUSTOMER.MANAGEMENT.CLIENT(ID),
