
--Purpose is to eventually create download files immediately
CREATE OR REPLACE TRANSIENT TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_QUEUE (
    APP_ORGANIZATION_ID VARCHAR NOT NULL,
    APP_BATCH_ID VARCHAR NOT NULL,
    QUEUED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PROCESSING_STATUS VARCHAR NOT NULL DEFAULT 'PENDING',
    PROCESSING_STARTED_TS TIMESTAMP_NTZ,
    PROCESSED_TS TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR,
    CREATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CLIENT_BATCH_DOWNLOAD_QUEUE
        PRIMARY KEY (APP_ORGANIZATION_ID, APP_BATCH_ID)
);