CREATE OR REPLACE TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_OUTPUT_CONFIGURATION (
    APP_ORGANIZATION_ID VARCHAR NOT NULL,
    APP_BATCH_ID VARCHAR NOT NULL,
    APP_FILE_ID VARCHAR NOT NULL,
    APP_PRESET_ID VARCHAR,
    APP_PRESET_LABEL VARCHAR,
    CONFIG_JSON VARIANT NOT NULL,
    CREATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CLIENT_BATCH_OUTPUT_CONFIGURATION
        PRIMARY KEY (APP_ORGANIZATION_ID, APP_BATCH_ID, APP_FILE_ID)
);