CREATE OR REPLACE TRANSIENT TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_READY_QUEUE (
    APP_ORGANIZATION_ID VARCHAR NOT NULL,
    APP_BATCH_ID VARCHAR NOT NULL,
    DOWNLOAD_OBJECT_KEY VARCHAR NOT NULL,
    DOWNLOAD_STATUS VARCHAR NOT NULL,
    QUEUED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PROCESSING_STATUS VARCHAR NOT NULL DEFAULT 'PENDING',
    PROCESSING_STARTED_TS TIMESTAMP_NTZ,
    PROCESSED_TS TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR,
    CREATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CLIENT_BATCH_DOWNLOAD_QUEUE
        PRIMARY KEY (APP_ORGANIZATION_ID, APP_BATCH_ID)
);


CREATE OR REPLACE TEMP TABLE CUSTOMER.FILE_PROCESSING.BACKUP_REINSERT AS
SELECT *
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_READY_QUEUE
WHERE APP_BATCH_ID = '550240cf-f4b4-49e0-a51c-49cade26eb1f';

DELETE
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_READY_QUEUE
WHERE APP_BATCH_ID IN
(
    SELECT APP_BATCH_ID FROM CUSTOMER.FILE_PROCESSING.BACKUP_REINSERT
);

INSERT INTO  CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_DOWNLOAD_READY_QUEUE 
SELECT * FROM CUSTOMER.FILE_PROCESSING.BACKUP_REINSERT;