CREATE OR REPLACE TRANSIENT TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_ENRICHMENT_STATUS (
    CLIENT_ID NUMBER(32,0) NOT NULL,
    BATCH_ID NUMBER(32,0) NOT NULL,
    APP_FILE_ID NUMBER(32,0) NOT NULL,
    ENRICHMENT_TYPE VARCHAR NOT NULL,
    ENRICHMENT_TYPE_CODE VARCHAR NOT NULL,
    ENRICHMENT_STATUS VARCHAR NOT NULL DEFAULT 'PENDING',
    STARTED_TS TIMESTAMP_NTZ,
    COMPLETED_TS TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR,
    CREATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CLIENT_BATCH_PROCESS_STATUS
        PRIMARY KEY (CLIENT_ID, APP_FILE_ID)
);