CREATE OR REPLACE TRANSIENT TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_COMPLETION_QUEUE (
    CLIENT_ID NUMBER(32,0) NOT NULL,
    BATCH_ID NUMBER(32,0) NOT NULL,
    QUEUED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PROCESSING_STATUS VARCHAR NOT NULL DEFAULT 'PENDING',
    PROCESSING_STARTED_TS TIMESTAMP_NTZ,
    PROCESSED_TS TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR,
    CREATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TS TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CLIENT_BATCH_COMPLETION_QUEUE
        PRIMARY KEY (CLIENT_ID, BATCH_ID)
);