CREATE OR REPLACE TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
(
    ID NUMBER(32,0) IDENTITY(1,1),
    CLIENT_ID NUMBER(32,0),
    FILE_NAME VARCHAR(1000),
    FILE_TYPE VARCHAR,
    RECORD_COUNT NUMBER(38,0),
    NOTES VARCHAR,
    CREATED_TS timestamp_ntz default current_timestamp()
    PROCESSED_TS timestamp_ntz

     CONSTRAINT foreign_key_client_id
        FOREIGN KEY (CLIENT_ID)
        REFERENCES CUSTOMER.MANAGEMENT.CLIENT(ID)
);

ALTER TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH ADD COLUMN APP_FILE_ID VARCHAR;

ALTER TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
DROP COLUMN PRORCESSED_TS;

ALTER TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
ADD COLUMN PROCESSED_TS timestamp_ntz;

ALTER TABLE CUSTOMER.FILE_PROCESSING.CLIENT_BATCH
ADD COLUMN DELIVERY_COMPLETE_TS timestamp_ntz;




SELECT *
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH;