create or replace transient table CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS (
    CLIENT_ID NUMBER(32,0),
    BATCH_ID NUMBER(32, 0),
    RECORD_ID varchar,
    PREDICTED_GENDER varchar,
    REPORTABLE_GENDER varchar,
    CONFIDENCE_LEVEL varchar,
    MAX_PROBABILITY number(10,6),
    PROBABILITY_GAP number(10,6),
    MODEL_VERSION varchar,
    PROCESSED_TS timestamp_ntz
);

ALTER TABLE CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS
ADD COLUMN FIRST_NAME_MISSING_FLAG NUMBER(1,0);

ALTER TABLE CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS
ADD COLUMN IS_RARE_NAME_FLAG NUMBER(1,0);

ALTER TABLE CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS
ADD COLUMN MALE_PROBABILITY NUMBER(10,6);

ALTER TABLE CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS
ADD COLUMN FEMALE_PROBABILITY NUMBER(10,6);
