
CREATE OR REPLACE TRANSIENT TABLE CUSTOMER.FILE_PROCESSING.GENDER_RESULTS_BATCH_SUMMARY (
    CLIENT_ID NUMBER(32,0),
    BATCH_ID NUMBER(32,0),
    MODEL_VERSION VARCHAR,
    METRIC_NAME VARCHAR,
    METRIC_TYPE VARCHAR,          -- 'REPORTABLE_GENDER', 'CONFIDENCE_LEVEL', 'RARE_NAME_CONFIDENCE'
    METRIC_LABEL VARCHAR,
    METRIC_VALUE NUMBER(32,6),
    PROCESSED_TS TIMESTAMP_NTZ
);

ALTER TABLE CUSTOMER.FILE_PROCESSING.GENDER_RESULTS_BATCH_SUMMARY 
ADD COLUMN METRIC_DISPLAY_TYPE VARCHAR;

ALTER TABLE CUSTOMER.FILE_PROCESSING.GENDER_RESULTS_BATCH_SUMMARY 
ADD COLUMN METRIC_LABEL_SORT VARCHAR;

ALTER TABLE CUSTOMER.FILE_PROCESSING.GENDER_RESULTS_BATCH_SUMMARY 
ADD COLUMN METRIC_SORT NUMBER(3,0);

