
CREATE ROLE SUPABASE_ADMIN;
GRANT USAGE ON DATABASE CUSTOMER TO ROLE SUPABASE_ADMIN  ;
GRANT USAGE ON SCHEMA CUSTOMER.MANAGEMENT TO ROLE SUPABASE_ADMIN  ;
GRANT SELECT, INSERT, UPDATE ON TABLE CUSTOMER.MANAGEMENT.CLIENT TO ROLE SUPABASE_ADMIN  ;
REVOKE ROLE ACCOUNTADMIN FROM USER SVC_SUPABASE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SUPABASE_ADMIN;

GRANT ROLE SUPABASE_ADMIN TO USER SVC_SUPABASE  ;

GRANT USAGE ON DATABASE INFERLYTICA TO ROLE SUPABASE_ADMIN;
GRANT USAGE ON SCHEMA INFERLYTICA.CONFIGURATION TO ROLE SUPABASE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA INFERLYTICA.CONFIGURATION TO ROLE SUPABASE_ADMIN  ;

GRANT USAGE ON SCHEMA CUSTOMER.FILE_PROCESSING TO ROLE SUPABASE_ADMIN  ;
GRANT  SELECT, INSERT, UPDATE ON TABLE  CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_OUTPUT_CONFIGURATION TO ROLE SUPABASE_ADMIN;
