
CREATE ROLE SUPABASE_ADMIN;
GRANT USAGE ON DATABASE CUSTOMER TO ROLE SUPABASE_ADMIN  ;
GRANT USAGE ON SCHEMA CUSTOMER.MANAGEMENT TO ROLE SUPABASE_ADMIN  ;
GRANT SELECT, INSERT, UPDATE ON TABLE CUSTOMER.MANAGEMENT.CLIENT TO ROLE SUPABASE_ADMIN  ;
REVOKE ROLE ACCOUNTADMIN FROM USER SVC_SUPABASE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SUPABASE_ADMIN;

GRANT ROLE SUPABASE_ADMIN TO USER SVC_SUPABASE  ;

GRANT USAGE ON DATABASE INFERLYTICA TO ROLE SUPABASE_ADMIN;
GRANT USAGE ON SCHEMA INFERLYTICA.CONFIGURATION TO ROLE SUPABASE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA INFERLYTICA.CONFIGURATION TO ROLE SUPABASE_ADMIN  ;

GRANT USAGE ON SCHEMA CUSTOMER.FILE_PROCESSING TO ROLE SUPABASE_ADMIN  ;
GRANT  SELECT, INSERT, UPDATE ON TABLE  CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_OUTPUT_CONFIGURATION TO ROLE SUPABASE_ADMIN;
GRANT USAGE ON PROCEDURE CUSTOMER.FILE_PROCESSING.PREPARE_SINGLE_DOWNLOAD(VARCHAR, VARCHAR) TO ROLE SUPABASE_ADMIN  ;

GRANT SELECT, UPDATE, INSERT ON TABLE CUSTOMER.MANAGEMENT.CREDIT_APPROVAL_RESULT_QUEUE TO ROLE SUPABASE_ADMIN;
 Deno.env.get("SNOWFLAKE_CREDIT_APPROVAL_QUEUE_TABLE")?.trim() ||
      "";
SELECT *
FROM CUSTOMER.FILE_PROCESSING.CLIENT_BATCH_OUTPUT_CONFIGURATION;

SELECT *
FROM INFERLYTICA.CONFIGURATION.ENRICHMENT_ATTRIBUTE_DETAIL

SELECT *
FROM CUSTOMER.FILE_PROCESSING.OUTPUT_GENDER_RESULTS;
{
  "attributes": [
    {
      "code": "GNDRPR",
      "label": "Gender Predictions"
    }
  ],
  "output_fields": [
    {
      "field_name": "RECORD_ID",
      "sort_order": null
    },
    {
      "field_name": "FIRST_NAME",
      "sort_order": null
    },
    {
      "field_name": "LAST_NAME",
      "sort_order": null
    },
    {
      "field_name": "ZIP",
      "sort_order": null
    },
    {
      "field_name": "MALE_PROBABILITY",
      "sort_order": 1
    },
    {
      "field_name": "FEMALE_PROBABILITY",
      "sort_order": 2
    },
    {
      "field_name": "GENDER_CONFIDENCE_LEVEL",
      "sort_order": 3
    },
    {
      "field_name": "PREDICTED_GENDER",
      "sort_order": 4
    }
  ],
  "retain_source_fields": true
}